castor_simplon/castor/config/routes.rb
Rails.application.routes.draw do

    root 'pages#home'
    get 'contact'             => 'pages#contact'
    get 'a_propos'            => 'pages#a_propos'
    get 'books'               => 'books#index'
    get 'books/:id'           => 'books#show'
    post 'books'              => 'books#create'
    patch 'books/:id'         => 'books#update'
    delete 'books/:id'        => 'books#destroy'

    

end

castor_simplon/castor/app/models/book.rb
class Book < ActiveRecord::Base
end

castor_simplon/castor/app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all
    end
    
    def create
        Book.create title: params[:title]
        redirect_to '/books'
    end
    
    def show
        @book = Book.find_by_id(params[:id])
    end
    
    def update
        Book.find_by_id(params[:id]).update title: params[:title]
        redirect_to "/books/#{params[:id]}"
    end
    
    def destroy
        Book.find_by_id(params[:id]).destroy
        redirect_to '/books'
    end
end

castor_simplon/castor/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def a_propos
  end
end

castor_simplon/castor/app/helpers/books_helper.rb
module BooksHelper
end

castor_simplon/castor/app/helpers/pages_helper.rb
module PagesHelper
end

castor_simplon/castor/app/views/books/index.html.erb
<h1>Liste des livres</h1>
  <% @books.each do |book| %>
    <p><a href="/books/<%= book.id %>"><%= book.title %></a></p>
  <% end %>

  <%= form_tag '/books', method: 'post' do %>
    <input type="text" name="title" />
    <input type="submit" value="Ajouter le livre" />
  <% end %>

<p><%= link_to'page 1', root_path %></p>
<p><%= link_to'page 2', contact_path %></p>
<p><%= link_to'page 3', a_propos_path %></p>
<p><%= link_to('liste des livres', books_path)%></p>

castor_simplon/castor/app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<%= form_tag "/books/#{@book.id}", method: 'patch' do %>
  <input type="text" name="title" value="<%= @book.title %>" />
  <input type="submit" value="Modifier le livre" />
<% end %>

<%= form_tag "/books/#{@book.id}", method: 'delete' do %>
  <input type="submit" value="Supprimer le livre" />
<% end %>

<p><%= link_to('Retourner à l\'index',books_url)%></p>

castor_simplon/castor/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Castor</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

castor_simplon/castor/app/views/pages/a_propos.html.erb
<h1>page 3</h1>
<p>3 eme page pour tester </p>
<p><%= link_to'page 1', root_path %></p>
<p><%= link_to'page 2', contact_path %></p>
<p><%= link_to'page 3', a_propos_path %></p>
<p><%= link_to('liste des livres', books_path)%></p>

castor_simplon/castor/app/views/pages/contact.html.erb
<h1>ma page de contact</h1>
<p>Ceci est ma premiére page de contact RoR</p>
<p><%= link_to'page 1', root_path %></p>
<p><%= link_to'page 2', contact_path %></p>
<p><%= link_to'page 3', a_propos_path %></p>
<p><%= link_to('liste des livres', books_path)%></p>

castor_simplon/castor/app/views/pages/home.html.erb
<h1>ma premiére page</h1>
<p>Ceci est ma premiére page crée avec RoR</p>
<p><%= link_to'page 1', root_path %></p>
<p><%= link_to'page 2', contact_path %></p>
<p><%= link_to'page 3', a_propos_path %></p>
<p><%= link_to('liste des livres', books_path)%></p>