gestion d une flotte de voiture/config/routes.rb
Rails.application.routes.draw do
    root 'personnes#index'
  resources :personnes
  resources :voitures
    

end

gestion d une flotte de voiture/app/models/personne.rb
class Personne < ActiveRecord::Base
end

gestion d une flotte de voiture/app/models/voiture.rb
class Voiture < ActiveRecord::Base
end

gestion d une flotte de voiture/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

gestion d une flotte de voiture/app/controllers/personnes_controller.rb
class PersonnesController < ApplicationController
  before_action :set_personne, only: [:show, :edit, :update, :destroy]

  # GET /personnes
  # GET /personnes.json
  def index
    @personnes = Personne.all
  end

  # GET /personnes/1
  # GET /personnes/1.json
  def show
  end

  # GET /personnes/new
  def new
    @personne = Personne.new
  end

  # GET /personnes/1/edit
  def edit
  end

  # POST /personnes
  # POST /personnes.json
  def create
    @personne = Personne.new(personne_params)

    respond_to do |format|
      if @personne.save
        format.html { redirect_to @personne, notice: 'Personne was successfully created.' }
        format.json { render :show, status: :created, location: @personne }
      else
        format.html { render :new }
        format.json { render json: @personne.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personnes/1
  # PATCH/PUT /personnes/1.json
  def update
    respond_to do |format|
      if @personne.update(personne_params)
        format.html { redirect_to @personne, notice: 'Personne was successfully updated.' }
        format.json { render :show, status: :ok, location: @personne }
      else
        format.html { render :edit }
        format.json { render json: @personne.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personnes/1
  # DELETE /personnes/1.json
  def destroy
    @personne.destroy
    respond_to do |format|
      format.html { redirect_to personnes_url, notice: 'Personne was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personne
      @personne = Personne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personne_params
      params.require(:personne).permit(:nom, :prenomb, :date_de_naissance)
    end
end

gestion d une flotte de voiture/app/controllers/voitures_controller.rb
class VoituresController < ApplicationController
  before_action :set_voiture, only: [:show, :edit, :update, :destroy]

  # GET /voitures
  # GET /voitures.json
  def index
    @voitures = Voiture.all
  end

  # GET /voitures/1
  # GET /voitures/1.json
  def show
  end

  # GET /voitures/new
  def new
    @voiture = Voiture.new
  end

  # GET /voitures/1/edit
  def edit
  end

  # POST /voitures
  # POST /voitures.json
  def create
    @voiture = Voiture.new(voiture_params)

    respond_to do |format|
      if @voiture.save
        format.html { redirect_to @voiture, notice: 'Voiture was successfully created.' }
        format.json { render :show, status: :created, location: @voiture }
      else
        format.html { render :new }
        format.json { render json: @voiture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voitures/1
  # PATCH/PUT /voitures/1.json
  def update
    respond_to do |format|
      if @voiture.update(voiture_params)
        format.html { redirect_to @voiture, notice: 'Voiture was successfully updated.' }
        format.json { render :show, status: :ok, location: @voiture }
      else
        format.html { render :edit }
        format.json { render json: @voiture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voitures/1
  # DELETE /voitures/1.json
  def destroy
    @voiture.destroy
    respond_to do |format|
      format.html { redirect_to voitures_url, notice: 'Voiture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voiture
      @voiture = Voiture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voiture_params
      params.require(:voiture).permit(:immatriculation, :couleur, :marque, :modele, :date_mise_en_service)
    end
end

gestion d une flotte de voiture/app/helpers/application_helper.rb
module ApplicationHelper
end

gestion d une flotte de voiture/app/helpers/personnes_helper.rb
module PersonnesHelper
end

gestion d une flotte de voiture/app/helpers/voitures_helper.rb
module VoituresHelper
end

gestion d une flotte de voiture/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjetRor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

gestion d une flotte de voiture/app/views/personnes/_form.html.erb
<%= form_for(@personne) do |f| %>
  <% if @personne.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personne.errors.count, "error") %> prohibited this personne from being saved:</h2>

      <ul>
      <% @personne.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :prenomb %><br>
    <%= f.text_field :prenomb %>
  </div>
  <div class="field">
    <%= f.label :date_de_naissance %><br>
    <%= f.date_select :date_de_naissance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

gestion d une flotte de voiture/app/views/personnes/edit.html.erb
<h1>Editing Personne</h1>

<%= render 'form' %>

<%= link_to 'Show', @personne %> |
<%= link_to 'Back', personnes_path %>

gestion d une flotte de voiture/app/views/personnes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Personnes</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenomb</th>
      <th>Date de naissance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personnes.each do |personne| %>
      <tr>
        <td><%= personne.nom %></td>
        <td><%= personne.prenomb %></td>
        <td><%= personne.date_de_naissance %></td>
        <td><%= link_to 'Show', personne %></td>
        <td><%= link_to 'Edit', edit_personne_path(personne) %></td>
        <td><%= link_to 'Destroy', personne, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personne', new_personne_path %>
<p><%= link_to('aller au listing des voitures', {:controller => 'voitures', :action => 'index'})%></p>

gestion d une flotte de voiture/app/views/personnes/new.html.erb
<h1>New Personne</h1>

<%= render 'form' %>

<%= link_to 'Back', personnes_path %>

gestion d une flotte de voiture/app/views/personnes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @personne.nom %>
</p>

<p>
  <strong>Prenomb:</strong>
  <%= @personne.prenomb %>
</p>

<p>
  <strong>Date de naissance:</strong>
  <%= @personne.date_de_naissance %>
</p>

<%= link_to 'Edit', edit_personne_path(@personne) %> |
<%= link_to 'Back', personnes_path %>

gestion d une flotte de voiture/app/views/voitures/_form.html.erb
<%= form_for(@voiture) do |f| %>
  <% if @voiture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voiture.errors.count, "error") %> prohibited this voiture from being saved:</h2>

      <ul>
      <% @voiture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :immatriculation %><br>
    <%= f.text_field :immatriculation %>
  </div>
  <div class="field">
    <%= f.label :couleur %><br>
    <%= f.text_field :couleur %>
  </div>
  <div class="field">
    <%= f.label :marque %><br>
    <%= f.text_field :marque %>
  </div>
  <div class="field">
    <%= f.label :modele %><br>
    <%= f.text_field :modele %>
  </div>
  <div class="field">
    <%= f.label :date_mise_en_service %><br>
    <%= f.date_select :date_mise_en_service %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

gestion d une flotte de voiture/app/views/voitures/edit.html.erb
<h1>Editing Voiture</h1>

<%= render 'form' %>

<%= link_to 'Show', @voiture %> |
<%= link_to 'Back', voitures_path %>

gestion d une flotte de voiture/app/views/voitures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Voitures</h1>

<table>
  <thead>
    <tr>
      <th>Immatriculation</th>
      <th>Couleur</th>
      <th>Marque</th>
      <th>Modele</th>
      <th>Date mise en service</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voitures.each do |voiture| %>
      <tr>
        <td><%= voiture.immatriculation %></td>
        <td><%= voiture.couleur %></td>
        <td><%= voiture.marque %></td>
        <td><%= voiture.modele %></td>
        <td><%= voiture.date_mise_en_service %></td>
        <td><%= link_to 'Show', voiture %></td>
        <td><%= link_to 'Edit', edit_voiture_path(voiture) %></td>
        <td><%= link_to 'Destroy', voiture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voiture', new_voiture_path %>
<p><%= link_to('aller au listing des personnes', {:controller => 'personnes', :action => 'index'})%></p>

gestion d une flotte de voiture/app/views/voitures/new.html.erb
<h1>New Voiture</h1>

<%= render 'form' %>

<%= link_to 'Back', voitures_path %>

gestion d une flotte de voiture/app/views/voitures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Immatriculation:</strong>
  <%= @voiture.immatriculation %>
</p>

<p>
  <strong>Couleur:</strong>
  <%= @voiture.couleur %>
</p>

<p>
  <strong>Marque:</strong>
  <%= @voiture.marque %>
</p>

<p>
  <strong>Modele:</strong>
  <%= @voiture.modele %>
</p>

<p>
  <strong>Date mise en service:</strong>
  <%= @voiture.date_mise_en_service %>
</p>

<%= link_to 'Edit', edit_voiture_path(@voiture) %> |
<%= link_to 'Back', voitures_path %>